# Site settings
title: "David Gitman's Resume"
description: "Multi-Exit, Multi-Failure Ecommerce Technologist."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "David Gitman"
resume_title:                   "Multi-Exit, Multi-Failure Ecommerce Technologist"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "david@gitman.net"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "(646) 878-9184"
resume_contact_address:         "Durham, NC"

resume_header_contact_info:     "Durham, NC • (646) 878-9184 • "david@gitman.net"
display_header_contact_info:    "true"

resume_header_intro: "<p><b>Over 23 years of success deploying technical solutions that drive dramatic growth in sales, profit and market share</b></p>

<p><b>Highly creative entrepreneur with a 23-year track record of innovation and success.</b> Strength in conceptualizing, recommending, architecting and aligning technology investments with evolving business, market and client needs.</p>

<p><b>Background includes leading the design and development of solutions for such industry leaders</b> as MediaLink Worldwide, eBay, ToysRUs.com and TheGlobe.com complemented by leading e-commerce development firm from $400K in revenues to over $8.5M in 4 years.</p>

<p><b>Successful in creating vision, identifying opportunities, building organizations, and delivering strong growth for start-up and established organizations</b> within intensively competitive Internet, eCommerce & New Media markets.</p>

<p><b>Change agent with strong build out, transformation and turnaround leadership.</b> Skilled in establishing, revitalizing, integrating and optimizing technologies, systems, teams and processes to reduce costs and achieve operational excellence. <b>Practiced in managing offshore teams.</b></p>

<p><b>Provide dedicated leadership in researching, evaluating and implementing emerging cloud computing, security, eCommerce, and business continuity</b> technologies, standards and best practices to mitigate risk, achieve compliance and ensure optimal uptime of core systems, services and environments.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
# resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/dgitman/resume"
  resume_twitter_url:           "https://twitter.com/dgitman"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  resume_facebook_url:          "https://www.facebook.com/dgitman"
  resume_linkedin_url:          "https://www.linkedin.com/in/dgitman/"
  resume_instagram_url:         "https://www.instagram.com/dgitman"
  resume_website_url:           "https://davidgitman.com"
  resume_medium_url:            "https://medium.com/@dgitman"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
